@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "Software" as System
participant "Dealership" as Dealership


User -> System: Click "Modify Dealership Profile"
System -> User: Present options(Add Dealership Name, Edit Dealership Name)
User -> System: Click "Add Dealership Name"
System -> Dealership: List dealerships without a name
User -> System: Select dealership
System -> User: Text fields to enter name
User -> System: Enter dealership name
System -> Dealership: setDealershipName()

@enduml
