@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "Software" as System
participant "Dealership" as Dealership
participant "Vehicle" as Vehicle

User -> System: Click "Modify Dealership Inventory"
System -> User: Present options (Enable Rent, Disable Rent, Remove Vehicle, Transfer Inventory)
User -> System: Click "Enable Rent"
System -> Dealership: List dealerships able to rent vehicles
alt No dealerships able to rent
    System -> User: Notify no dealerships currently renting
else Dealerships available
    System -> User: Present list of dealerships
    end

User -> System: Select dealership to modify
System -> Dealership: getDataMap()
alt No vehicles in dealership
    System -> User: notify to add vehicle(s)
 else Vehicles available
    System -> User: Present table of vehicles
    end

User -> System: Select vehicle(s) to enable rent
System -> Vehicle: enableRent()
System -> Dealership : Move vehicles to rental inventory
@enduml