'@author Christopher Engelhart
@startuml


System -> Dealership: getStatus_AcquiringVehicles()
System <- Dealership: result: receiving_vehicle status
    opt receiving_vehicle == true
        System -> Dealership: add_incoming_vehicle()
    end opt

@enduml